"""
Script to generate musical profile radar plots for EDM clusters (Figure 4).
Extracted and adapted from _ref_repo/project_alun_part/finetuned_model_500.ipynb
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from math import pi
from sklearn.cluster import KMeans
import pickle
import os
import re
import warnings
warnings.filterwarnings('ignore')

# --- Publication-quality defaults ---
plt.rcParams.update({
    'font.size': 14,
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'Times', 'DejaVu Serif'],
    'mathtext.fontset': 'stix',
    'figure.dpi': 100,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
})


# ────────────────────────────────────────────────────────────────
#  Data loading (from saved pkl — canonical pipeline output)
# ────────────────────────────────────────────────────────────────

def load_and_process_data():
    """Load pre-computed features from saved pkl (generated by run_pipeline.py)."""
    feature_matrix_path = 'results/pkl/feature_matrix.pkl'
    
    if not os.path.exists(feature_matrix_path):
        raise FileNotFoundError(
            f"Feature matrix not found at {feature_matrix_path}. "
            "Run run_pipeline.py first to generate it."
        )
    
    print("Loading pre-computed features from saved pkl...")
    with open(feature_matrix_path, 'rb') as f:
        fm = pickle.load(f)
    
    X_selected = pd.DataFrame(
        fm['X_selected'],
        columns=fm['feature_names'] if fm.get('feature_names') else None
    )
    y = pd.Series(fm['genre_labels'], name='genre')
    
    df = pd.read_csv('dataset/all_features_194.csv')
    
    print(f"Loaded: {X_selected.shape[0]} songs × {X_selected.shape[1]} features")
    return X_selected, y, df


def get_natural_clusters(X_selected, n_clusters=35):
    """Cluster using KMeans (k=35 to match paper).
    Data is already StandardScaler-transformed by the pipeline."""
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=20, max_iter=500)
    return kmeans.fit_predict(X_selected)


# ────────────────────────────────────────────────────────────────
#  Explicit feature → dimension mapping (no pattern matching, no
#  per-dimension cap).  Every numeric feature in all_features_194.csv
#  is assigned to exactly one of the six radar dimensions.
# ────────────────────────────────────────────────────────────────

# Energy – overall loudness / amplitude / dynamics
_ENERGY_FEATURES = [
    '2-Energym', '3-EnergyEntropym', '36-Energystd', '37-EnergyEntropystd',
    '78-beats_loudness.mean', '79-beats_loudness.stdev',
    'rms_mean', 'rms_std', 'rms_skew', 'rms_kurtosis',
    'dynamic_range_db', 'crest_factor',
    'energy_variance_8bar',
    'energy_ratio_low', 'energy_ratio_mid', 'energy_ratio_high',
]

# Danceability – groove / regularity / sidechain pumping
_DANCEABILITY_FEATURES = [
    '77-danceability',
    'beat_regularity',
    'sidechain_mod_depth', 'sidechain_mod_rate',
]

# Tempo – BPM / tempo histogram peaks
_TEMPO_FEATURES = [
    'meta.Bpm', '69-BPM', '71-bpm',
    '70-BPMconf',
    '72-bpm_histogram_first_peak_bpm', '73-bpm_histogram_first_peak_weight',
    '74-bpm_histogram_second_peak_bpm',
    '75-bpm_histogram_second_peak_spread', '76-bpm_histogram_second_peak_weight',
    'fourier_peak1_bpm', 'fourier_peak2_bpm', 'fourier_peak3_bpm',
    'fourier_peak4_bpm', 'fourier_peak5_bpm',
    'auto_peak1_bpm', 'auto_peak2_bpm', 'auto_peak3_bpm',
    'auto_peak4_bpm', 'auto_peak5_bpm',
]

# Harmonic complexity – chroma / pitch / harmonic-to-percussive ratio
_HARMONIC_FEATURES = [
    '22-ChromaVector1m', '23-ChromaVector2m', '24-ChromaVector3m',
    '25-ChromaVector4m', '26-ChromaVector5m', '27-ChromaVector6m',
    '28-ChromaVector7m', '29-ChromaVector8m', '30-ChromaVector9m',
    '31-ChromaVector10m', '32-ChromaVector11m', '33-ChromaVector12m',
    '34-ChromaDeviationm',
    '56-ChromaVector1std', '57-ChromaVector2std', '58-ChromaVector3std',
    '59-ChromaVector4std', '60-ChromaVector5std', '61-ChromaVector6std',
    '62-ChromaVector7std', '63-ChromaVector8std', '64-ChromaVector9std',
    '65-ChromaVector10std', '66-ChromaVector11std', '67-ChromaVector12std',
    '68-ChromaDeviationstd',
    'hp_ratio_mean', 'hp_ratio_std',
]

# Rhythmic density – onset patterns / percussive content / tempogram peaks
_RHYTHMIC_FEATURES = [
    '80-onset_rate', 'percussive_onset_density', 'kick_prominence',
    '81-beats_loudness_band_ratio.mean1', '82-beats_loudness_band_ratio.mean2',
    '83-beats_loudness_band_ratio.mean3', '84-beats_loudness_band_ratio.mean4',
    '85-beats_loudness_band_ratio.mean5', '86-beats_loudness_band_ratio.mean6',
    '87-beats_loudness_band_ratio.stdev1', '88-beats_loudness_band_ratio.stdev2',
    '89-beats_loudness_band_ratio.stdev3', '90-beats_loudness_band_ratio.stdev4',
    '91-beats_loudness_band_ratio.stdev5', '92-beats_loudness_band_ratio.stdev6',
    # tempogram peak strengths (non-BPM)
    'fourier_peak1_mean', 'fourier_peak1_std',
    'fourier_peak2_mean', 'fourier_peak2_std',
    'fourier_peak3_mean', 'fourier_peak3_std',
    'fourier_peak4_mean', 'fourier_peak4_std',
    'fourier_peak5_mean', 'fourier_peak5_std',
    'auto_peak1_mean', 'auto_peak1_std',
    'auto_peak2_mean', 'auto_peak2_std',
    'auto_peak3_mean', 'auto_peak3_std',
    'auto_peak4_mean', 'auto_peak4_std',
    'auto_peak5_mean', 'auto_peak5_std',
    'cyclic_fourier_peak1_s', 'cyclic_fourier_peak1_mean', 'cyclic_fourier_peak1_std',
    'cyclic_fourier_peak2_s', 'cyclic_fourier_peak2_mean', 'cyclic_fourier_peak2_std',
    'cyclic_fourier_peak3_s', 'cyclic_fourier_peak3_mean', 'cyclic_fourier_peak3_std',
    'cyclic_fourier_peak4_s', 'cyclic_fourier_peak4_mean', 'cyclic_fourier_peak4_std',
    'cyclic_fourier_peak5_s', 'cyclic_fourier_peak5_mean', 'cyclic_fourier_peak5_std',
    'cyclic_fourier_entropy', 'cyclic_fourier_peak_ratio',
    'cyclic_auto_peak1_s', 'cyclic_auto_peak1_mean', 'cyclic_auto_peak1_std',
    'cyclic_auto_peak2_s', 'cyclic_auto_peak2_mean', 'cyclic_auto_peak2_std',
    'cyclic_auto_peak3_s', 'cyclic_auto_peak3_mean', 'cyclic_auto_peak3_std',
    'cyclic_auto_peak4_s', 'cyclic_auto_peak4_mean', 'cyclic_auto_peak4_std',
    'cyclic_auto_peak5_s', 'cyclic_auto_peak5_mean', 'cyclic_auto_peak5_std',
    'cyclic_auto_entropy', 'cyclic_auto_peak_ratio',
]

# Electronic texture – spectral / timbral / MFCC / ZCR
_ELECTRONIC_FEATURES = [
    '1-ZCRm', '35-ZCRstd',
    '4-SpectralCentroidm', '5-SpectralSpreadm', '6-SpectralEntropym',
    '7-SpectralFluxm', '8-SpectralRolloffm',
    '38-SpectralCentroidstd', '39-SpectralSpreadstd', '40-SpectralEntropystd',
    '41-SpectralFluxstd', '42-SpectralRolloffstd',
    '9-MFCCs1m', '10-MFCCs2m', '11-MFCCs3m', '12-MFCCs4m', '13-MFCCs5m',
    '14-MFCCs6m', '15-MFCCs7m', '16-MFCCs8m', '17-MFCCs9m', '18-MFCCs10m',
    '19-MFCCs11m', '20-MFCCs12m', '21-MFCCs13m',
    '43-MFCCs1std', '44-MFCCs2std', '45-MFCCs3std', '46-MFCCs4std',
    '47-MFCCs5std', '48-MFCCs6std', '49-MFCCs7std', '50-MFCCs8std',
    '51-MFCCs9std', '52-MFCCs10std', '53-MFCCs11std', '54-MFCCs12std',
    '55-MFCCs13std',
    'spectral_contrast_band1_mean', 'spectral_contrast_band1_std',
    'spectral_contrast_band2_mean', 'spectral_contrast_band2_std',
    'spectral_contrast_band3_mean', 'spectral_contrast_band3_std',
    'spectral_contrast_band4_mean', 'spectral_contrast_band4_std',
    'spectral_contrast_band5_mean', 'spectral_contrast_band5_std',
    'spectral_contrast_band6_mean', 'spectral_contrast_band6_std',
    'spectral_contrast_band7_mean', 'spectral_contrast_band7_std',
    'spectral_flatness_mean', 'spectral_flatness_std',
    'spectral_bandwidth_mean', 'spectral_bandwidth_std',
    'spectral_mod_rate', 'spectral_mod_strength',
    'sub_bass_ratio',
]


def create_feature_mapping(df):
    """Build dimension → feature-list dict, keeping only columns present in *df*."""
    available = set(df.select_dtypes(include=[np.number]).columns)
    mapping = {
        'energy':              [f for f in _ENERGY_FEATURES       if f in available],
        'danceability':        [f for f in _DANCEABILITY_FEATURES  if f in available],
        'tempo':               [f for f in _TEMPO_FEATURES         if f in available],
        'harmonic_complexity': [f for f in _HARMONIC_FEATURES      if f in available],
        'rhythmic_density':    [f for f in _RHYTHMIC_FEATURES      if f in available],
        'electronic_texture':  [f for f in _ELECTRONIC_FEATURES    if f in available],
    }
    for dim, feats in mapping.items():
        print(f"  {dim}: {len(feats)} features")
    return mapping


# ────────────────────────────────────────────────────────────────
#  Profile computation  (z-score normalisation + p5/p95 percentile)
# ────────────────────────────────────────────────────────────────

def compute_adaptive_musical_profiles(df, cluster_labels, feature_mapping):
    """Compute p5/p95-scaled profiles per cluster.

    For each dimension:
      1. Z-score normalise every feature so all contribute equally.
      2. Average the normalised features per track → per-dimension score.
      3. Scale each cluster's mean score to 0–100 via p5/p95 linear
         interpolation (matching the original reference implementation)
         and clip to [0, 100].
    """
    profiles = {}
    for cid in np.unique(cluster_labels):
        mask = cluster_labels == cid
        profile = {}
        for dim, features in feature_mapping.items():
            if not features:
                profile[dim] = 50.0
                continue
            try:
                # Z-score normalize each feature so all contribute equally
                raw = df[features]
                mu = raw.mean()
                sigma = raw.std().replace(0, 1)
                normed = (raw - mu) / sigma
                dim_vals = normed.loc[mask].mean(axis=1)
                all_vals = normed.mean(axis=1)
            except Exception:
                profile[dim] = 50.0
                continue

            if len(all_vals) > 0:
                lo, hi = np.percentile(all_vals, 5), np.percentile(all_vals, 95)
                if hi > lo:
                    profile[dim] = float(np.clip(
                        (dim_vals.mean() - lo) / (hi - lo) * 100, 0, 100))
                else:
                    profile[dim] = 50.0
            else:
                profile[dim] = 50.0
        profiles[cid] = profile
    return profiles


# ────────────────────────────────────────────────────────────────
#  Radar-plot generation
# ────────────────────────────────────────────────────────────────

def create_musical_profile_figure(df, cluster_labels, y_true,
                                  save_path='paper/SMC/figs/paper/fig4_musical_profile.png'):
    """Create the 2×2 radar-plot figure (Figure 4 in the paper)."""

    # Feature mapping
    feature_mapping = create_feature_mapping(df)

    # Cluster info (purity)
    cluster_info = {}
    for cid in np.unique(cluster_labels):
        mask = cluster_labels == cid
        genres = y_true[mask]
        if len(genres) > 0:
            gc = genres.value_counts()
            cluster_info[cid] = {
                'dominant_genre': gc.index[0],
                'purity': gc.iloc[0] / len(genres),
                'size': mask.sum(),
            }

    # Profiles
    profiles = compute_adaptive_musical_profiles(df, cluster_labels, feature_mapping)

    # Sort by purity
    sorted_purity = sorted(cluster_info.items(), key=lambda x: x[1]['purity'], reverse=True)

    # ------ plotting ------
    fig = plt.figure(figsize=(12, 12))
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.25, wspace=0.15)

    categories = ['Energy', 'Dance.', 'Tempo', 'Harmonic', 'Rhythmic', 'Electronic']
    num_vars = len(categories)
    angles = [n / float(num_vars) * 2 * pi for n in range(num_vars)]
    angles += angles[:1]

    groups = [
        ("Top 5 Purest Clusters",       sorted_purity[:5]),
        ("Purest Clusters 6-10",        sorted_purity[5:10]),
        ("Top 5 Most Mixed Clusters",   sorted_purity[-5:]),
        ("Most Mixed Clusters 6-10",    sorted_purity[-10:-5]),
    ]

    color_schemes = [
        plt.cm.Set1(np.linspace(0.0, 0.5, 5)),     # Top 5 purest: vivid distinct hues
        plt.cm.tab10(np.linspace(0.5, 1.0, 5)),     # Purest 6-10: warm distinct hues
        plt.cm.Blues(np.linspace(0.4, 0.9, 5)),
        plt.cm.Greens(np.linspace(0.4, 0.9, 5)),
    ]

    # Background tints for each quadrant (very subtle)
    bg_colors = ['#FFF5F5', '#FFF8F0', '#F0F4FF', '#F0FFF0']

    for subplot_idx, (title, clusters) in enumerate(groups):
        ax = fig.add_subplot(gs[subplot_idx // 2, subplot_idx % 2], projection='polar')
        colors = color_schemes[subplot_idx]

        # — Modern grid: subtle concentric rings + radial spokes —
        ax.set_facecolor(bg_colors[subplot_idx])
        ax.grid(True, linestyle='-', alpha=0.15, color='#888888', linewidth=0.6)
        # Draw concentric reference rings
        for ring_val in [20, 40, 60, 80]:
            ring_angles = np.linspace(0, 2 * pi, 100)
            ax.plot(ring_angles, [ring_val] * 100,
                    linestyle=':', color='#AAAAAA', linewidth=0.5, alpha=0.6)

        for i, (cid, info) in enumerate(clusters[:5]):
            if cid in profiles:
                vals = [
                    profiles[cid].get('energy', 50),
                    profiles[cid].get('danceability', 50),
                    profiles[cid].get('tempo', 50),
                    profiles[cid].get('harmonic_complexity', 50),
                    profiles[cid].get('rhythmic_density', 50),
                    profiles[cid].get('electronic_texture', 50),
                ]
                vals += vals[:1]
                genre_short = info['dominant_genre'][:12]
                label = f"C{cid}: {genre_short} ({info['purity']:.0%})"
                # Glow effect: wider semi-transparent line behind
                ax.plot(angles, vals, linewidth=5, color=colors[i], alpha=0.15)
                # Main line
                ax.plot(angles, vals, 'o-', linewidth=2.2, label=label,
                        color=colors[i], markersize=5, markeredgecolor='white',
                        markeredgewidth=0.8, zorder=3)
                # Gradient-like fill
                ax.fill(angles, vals, alpha=0.12, color=colors[i])

        ax.set_theta_offset(pi / 2)
        ax.set_theta_direction(-1)
        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(categories, size=18, fontweight='normal', color='#444444')
        ax.set_ylim(0, 100)
        ax.set_yticks([20, 40, 60, 80])
        ax.set_yticklabels(['20', '40', '60', '80'], size=7, color='#999999')
        ax.spines['polar'].set_color('#CCCCCC')
        ax.spines['polar'].set_linewidth(0.8)
        ax.set_title(title, fontsize=18, fontweight='bold', pad=15, color='black')
        ax.legend(loc='upper left', bbox_to_anchor=(-0.18, 1.12),
                  fontsize=11, frameon=True, fancybox=True,
                  edgecolor='#CCCCCC', framealpha=0.9)

    fig.suptitle('Musical Profiles for clusters',
                 fontsize=27, fontweight='bold', color='black')
    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"Saved: {save_path}")
    plt.close()


# ────────────────────────────────────────────────────────────────
#  Main
# ────────────────────────────────────────────────────────────────

def main():
    X_selected, y, df = load_and_process_data()
    cluster_labels = get_natural_clusters(X_selected, n_clusters=35)
    create_musical_profile_figure(df, cluster_labels, y)


if __name__ == "__main__":
    main()
