"""
Script to generate musical profile radar plots for EDM clusters (Figure 4).
Extracted and adapted from _ref_repo/project_alun_part/finetuned_model_500.ipynb
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from math import pi
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pickle
import os
import re
import warnings
warnings.filterwarnings('ignore')

# --- Publication-quality defaults ---
plt.rcParams.update({
    'font.size': 14,
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'Times', 'DejaVu Serif'],
    'mathtext.fontset': 'stix',
    'figure.dpi': 100,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
})


# ────────────────────────────────────────────────────────────────
#  Data loading (from saved pkl — canonical pipeline output)
# ────────────────────────────────────────────────────────────────

def load_and_process_data():
    """Load pre-computed features from saved pkl (generated by main_analysis.py)."""
    feature_matrix_path = 'results/pkl/feature_matrix.pkl'
    
    if not os.path.exists(feature_matrix_path):
        raise FileNotFoundError(
            f"Feature matrix not found at {feature_matrix_path}. "
            "Run main_analysis.py first to generate it."
        )
    
    print("Loading pre-computed features from saved pkl...")
    with open(feature_matrix_path, 'rb') as f:
        fm = pickle.load(f)
    
    X_selected = pd.DataFrame(
        fm['X_selected'],
        columns=fm['feature_names'] if fm.get('feature_names') else None
    )
    y = pd.Series(fm['genre_labels'], name='genre')
    
    df = pd.read_csv('dataset/all_features_194.csv')
    
    print(f"Loaded: {X_selected.shape[0]} songs × {X_selected.shape[1]} features")
    return X_selected, y, df


def get_natural_clusters(X_selected, n_clusters=35):
    """Cluster using KMeans (k=35 to match paper)."""
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_selected)
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=20, max_iter=500)
    return kmeans.fit_predict(X_scaled)


# ────────────────────────────────────────────────────────────────
#  Adaptive feature mapping & profile computation
# ────────────────────────────────────────────────────────────────

def explore_dataset_features(df):
    """Categorise numeric columns by name patterns."""
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    categories = {
        'ENERGY':    [], 'SPECTRAL':  [], 'MFCC':      [],
        'CHROMA':    [], 'RHYTHM':    [], 'TIMBRE':     [],
        'META':      [], 'OTHER':     [],
    }
    for col in numeric_cols:
        cl = col.lower()
        if any(k in cl for k in ('energy', 'rms', 'loudness', 'amplitude')):
            categories['ENERGY'].append(col)
        elif any(k in cl for k in ('spectral', 'centroid', 'spread', 'rolloff', 'flux', 'entropy')):
            categories['SPECTRAL'].append(col)
        elif 'mfcc' in cl:
            categories['MFCC'].append(col)
        elif 'chroma' in cl or 'tonnetz' in cl or 'pitch' in cl:
            categories['CHROMA'].append(col)
        elif any(k in cl for k in ('rhythm', 'beat', 'onset', 'tempo', 'bpm', 'percussive', 'tempogram')):
            categories['RHYTHM'].append(col)
        elif 'zcr' in cl or 'timbre' in cl:
            categories['TIMBRE'].append(col)
        elif any(k in cl for k in ('meta', 'length', 'duration')):
            categories['META'].append(col)
        else:
            categories['OTHER'].append(col)
    return numeric_cols, categories


DIMENSION_CONFIG = {
    'energy': {
        'patterns': [r'.*energy.*', r'.*rms.*', r'.*loudness.*', r'.*amplitude.*'],
        'categories': ['ENERGY'],
    },
    'danceability': {
        'patterns': [r'.*danceability.*', r'.*groove.*', r'.*beat_strength.*'],
        'categories': ['RHYTHM'],
    },
    'tempo': {
        'patterns': [r'.*bpm.*', r'.*tempo.*', r'.*beat.*'],
        'categories': ['META', 'RHYTHM'],
    },
    'harmonic_complexity': {
        'patterns': [r'.*chroma.*', r'.*tonnetz.*', r'.*pitch.*', r'.*harmonic.*'],
        'categories': ['CHROMA'],
    },
    'rhythmic_density': {
        'patterns': [r'.*onset.*', r'.*tempogram.*', r'.*percussive.*', r'.*beat.*'],
        'categories': ['RHYTHM'],
    },
    'electronic_texture': {
        'patterns': [r'.*spectral.*', r'.*mfcc.*', r'.*timbre.*', r'.*centroid.*', r'.*rolloff.*'],
        'categories': ['SPECTRAL', 'MFCC', 'TIMBRE'],
    },
}


def create_adaptive_feature_mapping(feature_categories):
    """Map dataset columns to the six musical dimensions."""
    all_features = []
    for feats in feature_categories.values():
        all_features.extend(feats)

    feature_mapping = {}
    for dimension, config in DIMENSION_CONFIG.items():
        matched = []
        for pattern in config['patterns']:
            for feat in all_features:
                if re.match(pattern, feat.lower()) and feat not in matched:
                    matched.append(feat)
        for cat in config['categories']:
            if cat in feature_categories:
                for feat in feature_categories[cat]:
                    if feat not in matched:
                        matched.append(feat)
        feature_mapping[dimension] = matched[:5]  # max 5 per dimension
    return feature_mapping


def compute_adaptive_musical_profiles(df, cluster_labels, feature_mapping):
    """Compute percentile-ranked profiles per cluster."""
    fallback_features = {
        'energy':              lambda d: d.select_dtypes(include=[np.number]).std(axis=1),
        'danceability':        lambda d: d.select_dtypes(include=[np.number]).mean(axis=1),
        'tempo':               lambda d: d.select_dtypes(include=[np.number]).iloc[:, 0],
        'harmonic_complexity': lambda d: d.select_dtypes(include=[np.number]).var(axis=1),
        'rhythmic_density':    lambda d: d.select_dtypes(include=[np.number]).max(axis=1),
        'electronic_texture':  lambda d: d.select_dtypes(include=[np.number]).min(axis=1),
    }

    profiles = {}
    for cid in np.unique(cluster_labels):
        mask = cluster_labels == cid
        cluster_data = df[mask]
        profile = {}
        for dim, features in feature_mapping.items():
            try:
                if features:
                    dim_vals = cluster_data[features].mean(axis=1)
                    all_vals = df[features].mean(axis=1)
                else:
                    raise KeyError
            except Exception:
                dim_vals = fallback_features[dim](cluster_data)
                all_vals = fallback_features[dim](df)

            if len(all_vals) > 0:
                lo, hi = np.percentile(all_vals, 5), np.percentile(all_vals, 95)
                if hi > lo:
                    profile[dim] = float(np.clip((dim_vals.mean() - lo) / (hi - lo) * 100, 0, 100))
                else:
                    profile[dim] = 50.0
            else:
                profile[dim] = 50.0
        profiles[cid] = profile
    return profiles


# ────────────────────────────────────────────────────────────────
#  Radar-plot generation
# ────────────────────────────────────────────────────────────────

def create_musical_profile_figure(df, cluster_labels, y_true,
                                  save_path='paper/SMC/figs/paper/fig4_musical_profile.png'):
    """Create the 2×2 radar-plot figure (Figure 4 in the paper)."""

    # Feature mapping
    _, feature_categories = explore_dataset_features(df)
    feature_mapping = create_adaptive_feature_mapping(feature_categories)

    # Cluster info (purity)
    cluster_info = {}
    for cid in np.unique(cluster_labels):
        mask = cluster_labels == cid
        genres = y_true[mask]
        if len(genres) > 0:
            gc = genres.value_counts()
            cluster_info[cid] = {
                'dominant_genre': gc.index[0],
                'purity': gc.iloc[0] / len(genres),
                'size': mask.sum(),
            }

    # Profiles
    profiles = compute_adaptive_musical_profiles(df, cluster_labels, feature_mapping)

    # Sort by purity
    sorted_purity = sorted(cluster_info.items(), key=lambda x: x[1]['purity'], reverse=True)

    # ------ plotting ------
    fig = plt.figure(figsize=(12, 12))
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.25, wspace=0.15)

    categories = ['Energy', 'Dance.', 'Tempo', 'Harmonic', 'Rhythmic', 'Electronic']
    num_vars = len(categories)
    angles = [n / float(num_vars) * 2 * pi for n in range(num_vars)]
    angles += angles[:1]

    groups = [
        ("Top 5 Purest Clusters",       sorted_purity[:5]),
        ("Purest Clusters 6-10",        sorted_purity[5:10]),
        ("Top 5 Most Mixed Clusters",   sorted_purity[-5:]),
        ("Most Mixed Clusters 6-10",    sorted_purity[-10:-5]),
    ]

    color_schemes = [
        plt.cm.Set1(np.linspace(0.0, 0.5, 5)),     # Top 5 purest: vivid distinct hues
        plt.cm.tab10(np.linspace(0.5, 1.0, 5)),     # Purest 6-10: warm distinct hues
        plt.cm.Blues(np.linspace(0.4, 0.9, 5)),
        plt.cm.Greens(np.linspace(0.4, 0.9, 5)),
    ]

    # Background tints for each quadrant (very subtle)
    bg_colors = ['#FFF5F5', '#FFF8F0', '#F0F4FF', '#F0FFF0']

    for subplot_idx, (title, clusters) in enumerate(groups):
        ax = fig.add_subplot(gs[subplot_idx // 2, subplot_idx % 2], projection='polar')
        colors = color_schemes[subplot_idx]

        # — Modern grid: subtle concentric rings + radial spokes —
        ax.set_facecolor(bg_colors[subplot_idx])
        ax.grid(True, linestyle='-', alpha=0.15, color='#888888', linewidth=0.6)
        # Draw concentric reference rings
        for ring_val in [20, 40, 60, 80]:
            ring_angles = np.linspace(0, 2 * pi, 100)
            ax.plot(ring_angles, [ring_val] * 100,
                    linestyle=':', color='#AAAAAA', linewidth=0.5, alpha=0.6)

        for i, (cid, info) in enumerate(clusters[:5]):
            if cid in profiles:
                vals = [
                    profiles[cid].get('energy', 50),
                    profiles[cid].get('danceability', 50),
                    profiles[cid].get('tempo', 50),
                    profiles[cid].get('harmonic_complexity', 50),
                    profiles[cid].get('rhythmic_density', 50),
                    profiles[cid].get('electronic_texture', 50),
                ]
                vals += vals[:1]
                genre_short = info['dominant_genre'][:12]
                label = f"C{cid}: {genre_short} ({info['purity']:.0%})"
                # Glow effect: wider semi-transparent line behind
                ax.plot(angles, vals, linewidth=5, color=colors[i], alpha=0.15)
                # Main line
                ax.plot(angles, vals, 'o-', linewidth=2.2, label=label,
                        color=colors[i], markersize=5, markeredgecolor='white',
                        markeredgewidth=0.8, zorder=3)
                # Gradient-like fill
                ax.fill(angles, vals, alpha=0.12, color=colors[i])

        ax.set_theta_offset(pi / 2)
        ax.set_theta_direction(-1)
        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(categories, size=12, fontweight='bold', color='#444444')
        ax.set_ylim(0, 100)
        ax.set_yticks([20, 40, 60, 80])
        ax.set_yticklabels(['20', '40', '60', '80'], size=7, color='#999999')
        ax.spines['polar'].set_color('#CCCCCC')
        ax.spines['polar'].set_linewidth(0.8)
        ax.set_title(title, fontsize=14, fontweight='bold', pad=12, color='black')
        ax.legend(loc='upper left', bbox_to_anchor=(-0.15, 1.06),
                  fontsize=8.5, frameon=True, fancybox=True,
                  edgecolor='#CCCCCC', framealpha=0.9)

    fig.suptitle('Musical Profiles for clusters',
                 fontsize=27, fontweight='bold', color='black')
    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
    print(f"Saved: {save_path}")
    plt.close()


# ────────────────────────────────────────────────────────────────
#  Main
# ────────────────────────────────────────────────────────────────

def main():
    X_selected, y, df = load_and_process_data()
    cluster_labels = get_natural_clusters(X_selected, n_clusters=35)
    create_musical_profile_figure(df, cluster_labels, y)


if __name__ == "__main__":
    main()
